name: CI Pipeline       #nombre visible en la pestaña de actions

on:                     #eventos que dispara el workflow en push y pull request

  push:                 #cuando alguien hace push a la rama main
    branches: [ main ]  #.... a la rama main
  pull_request:         # cuando alguien hace pull request (pr)
    branches: [ main ]  #.... a la rama main

  workflow_dispatch:  #permite ejecución manual desde la UI de GitHub Actions 

  
  
jobs:                 #Acá van todos los jobs, es decir es la definición de los jobs que se ejecutarán en el workflow

    run-test:           #nombre del jbo
      name: Run Test    #nombre legible que aparecerá en la UI de GitHub Actions
      runs-on: ubuntu-latest  #define el sistema operativo donde se ejecutará el job, el ubuntu latest es la última versión de ubuntu disponible en GitHub Actions
        
      steps:            #Son los pasos en orden secuencial
        - name: Checkout Code  #nombre legible del paso
          uses: actions/checkout@v4  #acción que permite hacer checkout del código fuente del repositorio

        - name: Setup Node.js  #nombre legible del paso
          uses: actions/setup-node@v4  #acción que permite configurar Node.js en el runner
          with:
            node-version: '20'  #versión de Node.js específica a utilizar

        - name: Install Dependencies #nombre legible del paso para instalar dependencias del pack age.json
          run: npm ci  #comando para instalar dependencias de Node.js

        - name: Run Tests #nombre legible del paso para ejecutar los tests
          run: npm test  #comando para ejecutar los tests definidos en el package.json, es decir para que corran los tests de cron-ticker
