name: CI Pipeline       #nombre visible en la pestaña de actions

on:                     #eventos que dispara el workflow en push y pull request

  push:                 #cuando alguien hace push a la rama main
    branches: [ main ]  #.... a la rama main
  pull_request:         # cuando alguien hace pull request (pr)
    branches: [ main ]  #.... a la rama main

  workflow_dispatch:  #permite ejecución manual desde la UI de GitHub Actions 


#Variables a nivel del workflow, es decir que se pueden usar en todos los jobs y steps del workflow
env:
  NODE_VEERSION: "20"
  APP_NAME: "cron-ticker"
  
jobs:                 #Acá van todos los jobs, es decir es la definición de los jobs que se ejecutarán en el workflow

  build:
    runs-on: ubuntu-latest  #define el sistema operativo donde se ejecutará el job, el ubuntu latest es la última versión de ubuntu disponible en GitHub Actions
    
    #variables a nivel del job, es decir que se pueden usar en todos los steps del job
    env:
      BUILD_DIR: dist          #nombre del job

    steps:
      - uses: actions/checkout@v4  #step que hace checkout del repositorio, es decir clona el repositorio en el runner de GitHub Actions

      - name: Show Variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ env.NODE_VEERSION }}"

        #Variables al nivel del step, es decir que se pueden usar en ese step
      - name: Build
        run: npm run build
        env:
          APP_VERSION: '2.0.0'

      